apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}     # Unique identifier for the Helm Secret
  type: Opaque                         # Type of the Secret
data:
  mongo-root-username: {{ .Values.secrets.username | b64enc | quote }}  # Encoded data for the username
  mongo-root-password: {{ .Values.secrets.password | b64enc | quote }}  # Encoded data for the password
