apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  type: Opaque
data:
  mongo-root-username: {{ .Values.secrets.username | b64enc | quote }}
  mongo-root-password: {{ .Values.secrets.password | b64enc | quote }}
