apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}        # Unique identifier for the Helm Deployment
  labels:
    app: {{ .Values.deployment.app }}       # Label to identify resources related to this Deployment
spec:
  replicas: {{ .Values.replicaCount }}       # Number of replica pods to maintain
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}     # Selector label for the pods
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}  # Label for pods created by this Deployment
    spec:
      containers:
      - name: {{ .Values.container.name }}  # Name of the container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # Container image to use
        ports:
          - containerPort: {{ .Values.container.port }}  # Port to expose on the container
        env:
          - name: {{ .Values.env.username }}   # Environment variable for username
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.name }}
                key: {{ .Values.env.username }}  # Secret key for the username
          - name: {{ .Values.env.password }}   # Environment variable for password
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.name }}
                key: {{ .Values.env.password }}  # Secret key for the password
          - name: {{ .Values.env.server }}     # Environment variable for server
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: {{ .Values.env.server }}    # ConfigMap key for the server
