apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}               # Unique identifier for the Helm Service
spec:
  selector:
    app: {{ .Values.deployment.app }}            # Select pods with this label to expose
  type: {{ .Values.service.type }}               # Type of service (LoadBalancer, ClusterIP, etc.)
  ports:
    - protocol: TCP
      port: {{ .Values.service.ports.port }}     # Exposed port on the Service
      targetPort: {{ .Values.service.ports.targetPort }}   # Port on pods to forward traffic to
  {{- if eq .Values.service.type "LoadBalancer" }}
  nodePort: {{ .Values.service.ports.nodePort }}   # Node port (for LoadBalancer type)
  {{- end }}
