apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: name # Unique identifier for the Ingress resource
  annotations:
    kubernetes.io/ingress.class: "nginx" # Ingress controller class
spec:
  rules:
    - host: devops.com # Hostname associated with this Ingress
      http:
        paths:
          - path: / # Path-based routing
            backend:
              serviceName: my-service # Service to forward traffic to
              servicePort: 8080 # Service port to use
