apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap # Unique identifier for the ConfigMap
data:
  database_url: mongodb-service # Key-value pair: Key is 'database_url', value is 'mongodb-service'
