apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret # Unique identifier for the Secret
type: Opaque # Type of secret (Opaque for arbitrary data)
data:
  mongo-root-username: dXNlcm5hbWU= # Base64-encoded MongoDB admin username
  mongo-root-password: cGFzc3dvcmQ= # Base64-encoded MongoDB admin password
