apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb-service.yml # Include MongoDB service definition
  - mongodb-deployment.yml # Include MongoDB deployment definition
  - mongo-express-service.yml # Include Mongo Express service definition
  - mongo-express-deployment.yml # Include Mongo Express deployment definition
  - ingress.yml # Include Ingress definition

commonLabels:
  app: my-app # Common label applied to all resources
