apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Secret.name }} # Unique identifier for the Secret
type: {{ .Values.Secret.type }} # Type of secret (Opaque for arbitrary data)
data:
  mongo-root-username: {{ .Values.Secret.data.mongo-root-username }} # Base64-encoded MongoDB admin username
  mongo-root-password: {{ .Values.Secret.data.mongo-root-password }} # Base64-encoded MongoDB admin password
